"""godot/animation tools — AnimatedSprite2D setup."""

import zipfile
import io
import base64
from godot.bridge import GodotBridge

DIRECTIONS_8 = ["n", "ne", "e", "se", "s", "sw", "w", "nw"]
DIRECTION_ANGLES = {
    "n":  (-135, -90),
    "ne": (-90, -45),
    "e":  (-45, 45),
    "se": (45, 90),
    "s":  (90, 135),
    "sw": (135, 180),
    "w":  (-180, -135),
    "nw": (-135, -90),
}


async def setup_8dir_sprite(
    scene_path: str,
    node_path: str,
    archive_path: str,
    animation_name: str = "walk",
    fps: int = 8,
    bridge: GodotBridge = None,
    **_
) -> str:
    """
    Unpack a gensprite 8-direction archive and configure AnimatedSprite2D.
    Archive contains: n.png, ne.png, e.png, se.png, s.png, sw.png, w.png, nw.png
    """

    # Read archive from project
    archive_data = await bridge.call("read_file_b64", {"path": archive_path})
    zip_bytes = base64.b64decode(archive_data)

    # Extract each direction PNG into project
    assets_dir = archive_path.rsplit("/", 1)[0] + "/" + animation_name + "/"
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        for name in zf.namelist():
            direction = name.replace(".png", "").lower()
            if direction not in DIRECTIONS_8:
                continue
            img_b64 = base64.b64encode(zf.read(name)).decode()
            await bridge.call("write_file_b64", {
                "path": assets_dir + direction + ".png",
                "content": img_b64,
            })

    # Generate the direction helper script
    helper_script = _generate_8dir_script(animation_name, assets_dir, fps)
    script_path = scene_path.replace(".tscn", "_8dir.gd")
    await bridge.call("write_file", {"path": script_path, "content": helper_script})

    return (
        f"8-direction sprite set up:\n"
        f"  Textures: {assets_dir}\n"
        f"  Helper script: {script_path}\n"
        f"  Animations: {', '.join([animation_name + '_' + d for d in DIRECTIONS_8])}"
    )


async def setup_animated_sprite(
    scene_path: str,
    node_path: str,
    texture_path: str,
    animations: dict,
    bridge: GodotBridge = None,
    **_
) -> str:
    """
    Configure AnimatedSprite2D from a spritesheet.
    animations = {"idle": {"frames": 4, "fps": 8}, "run": {"frames": 6, "fps": 12}}
    """
    script = _generate_spritesheet_script(texture_path, animations)
    script_path = scene_path.replace(".tscn", "_anim_setup.gd")
    await bridge.call("write_file", {"path": script_path, "content": script})
    return f"AnimatedSprite2D configured with animations: {', '.join(animations.keys())}"


def _generate_8dir_script(anim_name: str, assets_dir: str, fps: int) -> str:
    return f"""extends Node

# Auto-generated by genengine — 8-direction animation helper
# Attach to the same node as AnimatedSprite2D, or call update_direction() from parent

const ASSETS_DIR = "{assets_dir}"
const FPS = {fps}
const DIRECTIONS = ["n", "ne", "e", "se", "s", "sw", "w", "nw"]

@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D

func _ready() -> void:
    _setup_animations()

func _setup_animations() -> void:
    var frames = SpriteFrames.new()
    for dir in DIRECTIONS:
        var anim = "{anim_name}_" + dir
        frames.add_animation(anim)
        frames.set_animation_speed(anim, FPS)
        var tex = load(ASSETS_DIR + dir + ".png")
        frames.add_frame(anim, tex)
    sprite.sprite_frames = frames

func update_direction(velocity: Vector2) -> void:
    if velocity == Vector2.ZERO:
        sprite.stop()
        return
    var angle = rad_to_deg(velocity.angle())
    var dir = _angle_to_dir(angle)
    var anim = "{anim_name}_" + dir
    if sprite.animation != anim:
        sprite.play(anim)

func _angle_to_dir(angle: float) -> String:
    # Normalize to 0-360
    angle = fmod(angle + 360, 360)
    if angle < 22.5 or angle >= 337.5:
        return "e"
    elif angle < 67.5:
        return "se"
    elif angle < 112.5:
        return "s"
    elif angle < 157.5:
        return "sw"
    elif angle < 202.5:
        return "w"
    elif angle < 247.5:
        return "nw"
    elif angle < 292.5:
        return "n"
    else:
        return "ne"
"""


def _generate_spritesheet_script(texture_path: str, animations: dict) -> str:
    lines = [
        "extends Node",
        "# Auto-generated by genengine — spritesheet animation setup",
        "",
        f'const TEXTURE_PATH = "{texture_path}"',
        "",
        "@onready var sprite: AnimatedSprite2D = $AnimatedSprite2D",
        "",
        "func _ready() -> void:",
        "    _setup_animations()",
        "",
        "func _setup_animations() -> void:",
        "    var tex = load(TEXTURE_PATH)",
        "    var frames = SpriteFrames.new()",
        "    var col = 0",
        "",
    ]
    for anim_name, cfg in animations.items():
        frame_count = cfg.get("frames", 1)
        fps = cfg.get("fps", 8)
        lines += [
            f'    frames.add_animation("{anim_name}")',
            f'    frames.set_animation_speed("{anim_name}", {fps})',
            f'    for i in {frame_count}:',
            f'        var atlas = AtlasTexture.new()',
            f'        atlas.atlas = tex',
            f'        atlas.region = Rect2(col * 64, 0, 64, 64)  # adjust size if needed',
            f'        frames.add_frame("{anim_name}", atlas)',
            f'        col += 1',
            '',
        ]
    lines.append("    sprite.sprite_frames = frames")
    return "\n".join(lines)
