"""godot/resources tools — TileSet, PhysicsMaterial, and other .tres resources."""

from godot.bridge import GodotBridge


async def create_tileset(
    output_path: str,
    texture_path: str,
    tile_size: int = 16,
    bridge: GodotBridge = None,
    **_
) -> str:
    """Create a TileSet resource (.tres) from a tileset texture."""
    uid = await bridge.generate_uid()
    texture_uid = await bridge.generate_uid()

    content = f"""[gd_resource type="TileSet" load_steps=2 format=3 uid="{uid}"]

[ext_resource type="Texture2D" path="{texture_path}" id="1_{texture_uid}"]

[resource]
tile_size = Vector2i({tile_size}, {tile_size})
sources/0 = SubResource("TileSetAtlasSource_0")

[sub_resource type="TileSetAtlasSource" id="TileSetAtlasSource_0"]
texture = ExtResource("1_{texture_uid}")
texture_region_size = Vector2i({tile_size}, {tile_size})
"""

    await bridge.write_file(output_path, content)
    return f"TileSet created: {output_path} (tile_size={tile_size})"


async def create_save_system(
    script_path: str,
    fields: list[str],
    bridge: GodotBridge = None,
    **_
) -> str:
    """
    Generate a SaveManager.gd autoload script.
    fields = ["score", "level", "player_position", "inventory"]
    """
    default_values = {f: _default_for_field(f) for f in fields}
    defaults_str = "\n    ".join([f'"{f}": {v},' for f, v in default_values.items()])

    script = f"""extends Node
# Auto-generated by genengine — Save System

const SAVE_PATH = "user://save.json"

var data: Dictionary = {{
    {defaults_str}
}}

func save() -> void:
    var file = FileAccess.open(SAVE_PATH, FileAccess.WRITE)
    file.store_string(JSON.stringify(data))

func load_save() -> void:
    if not FileAccess.file_exists(SAVE_PATH):
        return
    var file = FileAccess.open(SAVE_PATH, FileAccess.READ)
    var parsed = JSON.parse_string(file.get_as_text())
    if parsed:
        data.merge(parsed, true)

func reset() -> void:
    data = {{
        {defaults_str}
    }}
    save()
"""

    await bridge.write_file(script_path, script)
    return f"SaveManager created: {script_path}\nFields: {', '.join(fields)}\nAdd as Autoload in Project Settings."


def _default_for_field(name: str):
    if "position" in name: return "Vector2.ZERO"
    if "score" in name or "level" in name or "count" in name: return "0"
    if "inventory" in name or "items" in name: return "[]"
    return '""'
